/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fastpitchexpert;

import lanzamientos.DescrTipoLanzamiento;

/**
 *
 * @author Luuu
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        descrPanel.setVisible(false);
        questionPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_lbl = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btn_new = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_info = new javax.swing.JButton();
        btn_help = new javax.swing.JButton();
        questionPanel = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        question_options = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        option_description = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        question_lbl = new javax.swing.JTextArea();
        descrPanel = new javax.swing.JPanel();
        DescriptionPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        descrImgPanel = new javax.swing.JPanel();
        descrImg = new javax.swing.JLabel();
        description_label = new javax.swing.JLabel();
        description_text = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fastpitch Expert");
        setResizable(false);

        bg_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/bg.png"))); // NOI18N

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToolBar1.setRollover(true);

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/nuevo.png"))); // NOI18N
        btn_new.setToolTipText("Nuevo Lanzamiento");
        btn_new.setFocusable(false);
        btn_new.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_new.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/nuevo_over.png"))); // NOI18N
        btn_new.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_new);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(filler1);
        jToolBar1.add(jSeparator3);

        btn_info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/about.png"))); // NOI18N
        btn_info.setToolTipText("Acerca de");
        btn_info.setFocusable(false);
        btn_info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_info.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/about_over.png"))); // NOI18N
        btn_info.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_info);

        btn_help.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/help.png"))); // NOI18N
        btn_help.setToolTipText("Ayuda");
        btn_help.setFocusable(false);
        btn_help.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btn_help.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_help.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/res/help_over.png"))); // NOI18N
        btn_help.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_helpActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_help);

        questionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Preguntas"));
        questionPanel.setMaximumSize(new java.awt.Dimension(600, 400));

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/next32.png"))); // NOI18N
        btnNext.setText("Siguiente");
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnNext.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/prev32.png"))); // NOI18N
        btnPrev.setText("Anterior");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        question_options.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        question_options.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        question_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question_optionsActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        option_description.setBackground(new java.awt.Color(240, 240, 240));
        option_description.setColumns(20);
        option_description.setEditable(false);
        option_description.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        option_description.setLineWrap(true);
        option_description.setRows(5);
        option_description.setText("Descripcion item 1");
        option_description.setWrapStyleWord(true);
        option_description.setBorder(null);
        jScrollPane1.setViewportView(option_description);

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        question_lbl.setBackground(new java.awt.Color(240, 240, 240));
        question_lbl.setColumns(20);
        question_lbl.setEditable(false);
        question_lbl.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        question_lbl.setLineWrap(true);
        question_lbl.setRows(2);
        question_lbl.setText("¿Pregunta?");
        question_lbl.setWrapStyleWord(true);
        question_lbl.setBorder(null);
        jScrollPane2.setViewportView(question_lbl);

        javax.swing.GroupLayout questionPanelLayout = new javax.swing.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(question_options, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(questionPanelLayout.createSequentialGroup()
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext)))
                .addContainerGap())
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(question_options, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(questionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrev))
                .addContainerGap())
        );

        descrPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Descripción"));
        descrPanel.setFocusable(false);
        descrPanel.setMinimumSize(new java.awt.Dimension(380, 210));
        descrPanel.setPreferredSize(new java.awt.Dimension(391, 210));

        DescriptionPane.setBorder(null);
        DescriptionPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        DescriptionPane.setAutoscrolls(true);
        DescriptionPane.setPreferredSize(new java.awt.Dimension(368, 433));

        jPanel1.setPreferredSize(new java.awt.Dimension(440, 427));

        descrImgPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.white, null, null));

        descrImg.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        descrImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/fastpitch-softball-clipart-08.jpg"))); // NOI18N

        javax.swing.GroupLayout descrImgPanelLayout = new javax.swing.GroupLayout(descrImgPanel);
        descrImgPanel.setLayout(descrImgPanelLayout);
        descrImgPanelLayout.setHorizontalGroup(
            descrImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descrImgPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(descrImg))
        );
        descrImgPanelLayout.setVerticalGroup(
            descrImgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, descrImgPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(descrImg))
        );

        description_label.setFont(new java.awt.Font("Berlin Sans FB", 2, 24)); // NOI18N
        description_label.setText("FastBall");

        description_text.setBackground(new java.awt.Color(240, 240, 240));
        description_text.setColumns(20);
        description_text.setEditable(false);
        description_text.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        description_text.setLineWrap(true);
        description_text.setRows(20);
        description_text.setWrapStyleWord(true);
        description_text.setAutoscrolls(false);
        description_text.setMinimumSize(new java.awt.Dimension(164, 140));
        description_text.setVerifyInputWhenFocusTarget(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description_text, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(description_label, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(descrImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(description_label)
                .addGap(18, 18, 18)
                .addComponent(description_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(descrImgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(424, Short.MAX_VALUE)))
        );

        DescriptionPane.setViewportView(jPanel1);

        javax.swing.GroupLayout descrPanelLayout = new javax.swing.GroupLayout(descrPanel);
        descrPanel.setLayout(descrPanelLayout);
        descrPanelLayout.setHorizontalGroup(
            descrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        descrPanelLayout.setVerticalGroup(
            descrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DescriptionPane, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(questionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(descrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(bg_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(questionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(bg_lbl)
        );

        questionPanel.getAccessibleContext().setAccessibleName("");
        descrPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
       if (FastpitchExpert.getInstance().hayPrevia()) {
            _preguntaActual = FastpitchExpert.getInstance().getPreviaPregunta();
            actualizarElementos();
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        if (FastpitchExpert.getInstance().hayProxima()) {
            _preguntaActual = FastpitchExpert.getInstance().getProximaPregunta();
            actualizarElementos();
        }
        else {
            btnNext.setEnabled(false);
            procesarRespuestas();
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        FastpitchExpert.getInstance().init();
        questionPanel.setVisible(true);
        descrPanel.setVisible(true);
        bg_lbl.setVisible(false);
        _preguntaActual = FastpitchExpert.getInstance().getProximaPregunta();
        limpiarResultado();
        actualizarElementos();
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_infoActionPerformed

    private void btn_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_helpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_helpActionPerformed

    private void question_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question_optionsActionPerformed
        try{
            if (!_actualizando) {
                actualizarRespuesta();
                _preguntaActual.elegirRespuesta(question_options.getSelectedIndex());
            }
        }catch(Exception e) {}
    }//GEN-LAST:event_question_optionsActionPerformed

    
    //---------------------------- Mi codigo aca! -------------------------//
    
    private Pregunta _preguntaActual;
    private boolean _actualizando = false;
    
    private void actualizarElementos() {
        _actualizando = true;
        actualizarBotones();
        actualizarPregunta();
        _actualizando = false;
    }
    
    private void actualizarBotones() {
        if (! FastpitchExpert.getInstance().hayProxima()) 
            btnNext.setText("Ver Resultado");
        else
            btnNext.setText("Siguiente");
        btnPrev.setEnabled(FastpitchExpert.getInstance().hayPrevia());
        limpiarResultado();
    }
    
    private void actualizarPregunta() {
        question_lbl.setText(_preguntaActual.pregunta);
        question_options.removeAllItems();
        for (int i=0; i<_preguntaActual.respuestas.size(); ++i) {
            question_options.addItem(_preguntaActual.respuestas.get(i));
        }
        question_options.setSelectedIndex(_preguntaActual.respuestaElegida());
        actualizarRespuesta();
    }
    
    private void actualizarRespuesta() {
        Respuesta r = (Respuesta) question_options.getSelectedItem();
        option_description.setText(r.descripcion);
    }
    
    private void limpiarResultado() {
        btnNext.setEnabled(true);
        description_label.setText("");
        description_text.setText("");
    }
    
    private void procesarRespuestas() {
        DescrTipoLanzamiento resultado = FastpitchExpert.getInstance().obtenerResultado();
        if(resultado != null){
            description_label.setText(resultado.tipoLanzamiento);
            description_text.setText(resultado.descripcion);
            System.out.println(resultado.tipoLanzamiento);
        }
        else {
            description_label.setText("Sin Resultado");
            System.out.println("Sin Resultado");
        }
    }
    
    //-------------------------- ^ Mi codigo aca! ^ -----------------------//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DescriptionPane;
    private javax.swing.JLabel bg_lbl;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btn_help;
    private javax.swing.JButton btn_info;
    private javax.swing.JButton btn_new;
    private javax.swing.JLabel descrImg;
    private javax.swing.JPanel descrImgPanel;
    private javax.swing.JPanel descrPanel;
    private javax.swing.JLabel description_label;
    private javax.swing.JTextArea description_text;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea option_description;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JTextArea question_lbl;
    private javax.swing.JComboBox question_options;
    // End of variables declaration//GEN-END:variables
        
}
