//Agregar el import de los paquetes y clases necesarias



rule "Fastball"
    when
        lanzador : Lanzador(distPeso == 'Medio', pies == 'NoAlineado', soltadoPelota == 'Medio', movMunieca == 'Medio', traza == 'Recta', velocidad == 'Alta' )
    then
        System.out.println("Lanzamiento: " + lanzador.tipoLanzamiento());
        lanzador.setLanzamiento("Fastball");
        
end
 
rule "Changeup"
    when
        lanzador : Lanzador(distPeso == 'Medio', pies == 'Alineado', soltadoPelota == 'Medio', movMunieca == 'Poco', traza == 'Recta', velocidad == 'Baja' )
    then
        System.out.println("Lanzamiento: " + lanzador.tipoLanzamiento());
        lanzador.setLanzamiento("Changeup");
        
end 
 
rule "Curveball"
    when
        lanzador : Lanzador(distPeso == 'Medio', pies == 'Alineado', soltadoPelota == 'Medio', movMunieca == 'Mucho', traza == 'Curva', velocidad == 'Media' )
    then
        System.out.println("Lanzamiento: " + lanzador.tipoLanzamiento());
        lanzador.setLanzamiento("Curveball");
        
end

rule "Riseball"
    when
        lanzador : Lanzador(distPeso == 'Atras', pies == 'Alineado', soltadoPelota == 'Medio', movMunieca == 'Mucho', traza == 'Trepa', velocidad == 'Media' )
    then
        System.out.println("Lanzamiento: " + lanzador.tipoLanzamiento());
        lanzador.setLanzamiento("Riseball");
        
end

rule "Dropball"
    when
        lanzador : Lanzador(distPeso == 'Delante', pies == 'Alineado', soltadoPelota == 'Atras', movMunieca == 'Medio', traza == 'Baja', velocidad == 'Media' )
    then
        System.out.println("Lanzamiento: " + lanzador.tipoLanzamiento());
        lanzador.setLanzamiento("Dropball");
        
end


rule "Screwball"
    when
        lanzador : Lanzador(distPeso == 'Medio', pies == 'Alineado', soltadoPelota == 'Delante', movMunieca == 'Mucho', traza == 'Curva', velocidad == 'Media' )
    then
        System.out.println("Lanzamiento: " + lanzador.tipoLanzamiento());
        lanzador.setLanzamiento("Screwball");
        
end
